development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: notset_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: notset_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: notset_rails
  pool: 5
  timeout: 5000