# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26dbba2226e2b13336bce7219217934d629c2a0cc38e1dff9adfaea70ec75783c6ec63bf0347f551474c3b2b43e8bcbecbd65de4bcec8e4b2eb4a3643405b687
  google_id: 489036066949-4juk9v4okfepnsev38jktjjdnojb22t0.apps.googleusercontent.com
  google_secret: uUiCzVZY6o-_7eyGGz12kh4R
  state: SecureRandom.hex
  google_redirect: http://localhost:3000/oauth2callback
  fb_id: 815852498478185
  fb_secret: 4d8bececac344639ed0c429b406f7320
  fb_redirect: http://localhost:3000/fboauth2callback

test:
  secret_key_base: 53e43d2420d98d633292a48710040f7bde2c586b364887619dc653f29a0cab9ebdd1729ed0264969d6d82029b8ad7c8e865472ac4cd2f06cd683cc66e6d6b70f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_id: 489036066949-4juk9v4okfepnsev38jktjjdnojb22t0.apps.googleusercontent.com
  client_secret: uUiCzVZY6o-_7eyGGz12kh4R
  state: SecureRandom.hex
  google_redirect: http://notset.herokuapp.com/oauth2callback
  fb_id: 815852498478185
  fb_secret: 4d8bececac344639ed0c429b406f7320
  fb_redirect: http://notset.herokuapp.com/fboauth2callback

